### ISSUE TITLE
 [self.tableView relaxHeader];  how to do？

### ISSUE THREAD

**Issue by sujiewen** [xiekw2010/DXRefresh#1]
[self.tableView relaxHeader]; how to do？

**Comment by xiekw2010** [comment]
// your ViewController which has add header
-(void)viewDidAppear:(BOOL)animated
{
   [super viewDidAppear:animated];
   [self.tableView relaxHeader];
}

**Comment by sujiewen** [comment]
The method does not exist？！

**Comment by xiekw2010** [comment]
@sujiewen does the readme help you?
