### ISSUE TITLE
App crashes due to observers contentsize and contentoffset

### ISSUE THREAD

**Issue by koushikv04** [xiekw2010/DXRefresh#2]
An instance 0x7ffbc48ebe00 of class UITableView was deallocated while key value observers were still registered with it. Observation info was leaked, and may even become mistakenly attached to some other object. Set a breakpoint on NSKVODeallocateBreak to stop here in the debugger. Here's the current observation info:
<NSKeyValueObservationInfo 0x7ffbc608ea80> (
<NSKeyValueObservance 0x7ffbc3ea18f0: Observer: 0x7ffbc6164fa0, Key path: contentSize, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7ffbc3ea1860>
<NSKeyValueObservance 0x7ffbc608ea10: Observer: 0x7ffbc6164fa0, Key path: contentOffset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7ffbc60738d0>

Please provide a solution to this problem

**Comment by xiekw2010** [comment]
Did you use the latest version?

**Comment by koushikv04** [comment]
Yeah, the fix is available in the latest code.Thank you
